"""Reader for FFT-based linearity and IIP3 estimation outputs.

This module defines a reader for ngspice FFT output files used to estimate
linearity metrics. It extracts fundamental and third-order intermodulation
components, converts voltage magnitudes to power in dBm, and computes IIP3.
"""

from pathlib import Path
from typing import Union

import numpy as np
import pandas as pd

from simulator.ngspice.readers.base import BaseReader


class LinearityReader(BaseReader):
    """Reader that estimates IIP3 from FFT output samples.

    This reader parses FFT output generated by a two-tone transient simulation.
    It identifies the output magnitudes near the fundamental tones and
    third-order intermodulation frequencies, then computes input-referred IIP3.
    """

    def _read_impl(
        self,
        result_path: Union[str, Path],
        Vin_amp: float = 5e-3,
        f1: float = 2.399e9,
        f2: float = 2.401e9,
        R_load: float = 50,
    ) -> pd.DataFrame:
        """Parse FFT output and compute derived linearity metrics.

        Parameters
        ----------
        result_path : str or pathlib.Path
            Path to the FFT output file.
        Vin_amp : float, optional
            Input tone voltage amplitude used for IIP3 estimation. The default
            is ``5e-3``.
        f1 : float, optional
            First input tone frequency in Hz. The default is ``2.399e9``.
        f2 : float, optional
            Second input tone frequency in Hz. The default is ``2.401e9``.
        R_load : float, optional
            Load resistance in ohms used to convert voltage magnitude to power.
            The default is ``50``.

        Returns
        -------
        pandas.DataFrame
            Single-row dataframe containing ``Pin_dBm``,
            ``Pfund_dBm_avg``, ``Pim3_dBm_avg``, and ``IIP3_dBm``.

        Raises
        ------
        StopIteration
            If the FFT output does not contain a ``Values:`` section.
        ValueError
            If FFT value lines cannot be parsed into numeric frequency, real,
            and imaginary components.
        """

        with open(result_path, encoding="utf-8") as f:
            lines = f.readlines()

        start = (
            next(
                idx
                for idx, line in enumerate(lines)
                if line.strip().startswith("Values:")
            )
            + 1
        )
        data_lines = [line.strip() for line in lines[start:] if line.strip()]

        freq_lines = data_lines[0::2]
        val_lines = data_lines[1::2]

        freqs, reals, imags = [], [], []

        for f_line, v_line in zip(freq_lines, val_lines):
            parts = f_line.split()
            freq_val = parts[1].split(",")[0]
            freqs.append(float(freq_val))

            real, imag = v_line.split(",")
            reals.append(float(real))
            imags.append(float(imag))

        df = pd.DataFrame(
            {
                "frequency": freqs,
                "real": reals,
                "imag": imags,
            }
        )
        df["vout"] = df["real"] + 1j * df["imag"]
        df["mag"] = np.abs(df["vout"])

        im3_1 = 2 * f1 - f2
        im3_2 = 2 * f2 - f1

        def nearest_val(freq):
            """Return the magnitude at the nearest sampled frequency.

            Parameters
            ----------
            freq : float
                Target frequency in Hz.

            Returns
            -------
            float
                Voltage magnitude at the nearest available FFT frequency bin.
            """

            return df.iloc[(df["frequency"] - freq).abs().argmin()]["mag"]

        v_fund1 = nearest_val(f1)
        v_fund2 = nearest_val(f2)
        v_im3_1 = nearest_val(im3_1)
        v_im3_2 = nearest_val(im3_2)

        def p_dbm(v_mag, resistance):
            """Convert voltage magnitude to power in dBm.

            Parameters
            ----------
            v_mag : float
                Voltage magnitude.
            resistance : float
                Load resistance in ohms.

            Returns
            -------
            float
                Power value in dBm.
            """

            power = v_mag**2 / (2 * resistance)
            return np.real(10 * np.log10(power * 1e3 + 1e-30))

        pfund_dbm_avg = np.mean(
            [
                p_dbm(v_fund1, R_load),
                p_dbm(v_fund2, R_load),
            ]
        )
        pim3_dbm_avg = np.mean(
            [
                p_dbm(v_im3_1, R_load),
                p_dbm(v_im3_2, R_load),
            ]
        )
        pin_dbm = p_dbm(Vin_amp, R_load)
        iip3_dbm = pin_dbm + (pfund_dbm_avg - pim3_dbm_avg) / 2

        return pd.DataFrame(
            {
                "Pin_dBm": [pin_dbm],
                "Pfund_dBm_avg": [pfund_dbm_avg],
                "Pim3_dBm_avg": [pim3_dbm_avg],
                "IIP3_dBm": [iip3_dbm],
            }
        )

    def _read_metrics_impl(self, result_path: Union[str, Path]) -> dict:
        """Extract the scalar IIP3 metric.

        Parameters
        ----------
        result_path : str or pathlib.Path
            Path to the FFT output file.

        Returns
        -------
        dict[str, float]
            Dictionary containing the scalar ``"IIP3_dBm"`` value.
        """

        result = self._read_impl(result_path)
        return {"IIP3_dBm": float(result["IIP3_dBm"].iloc[0])}


__all__ = ["LinearityReader"]
"""list[str]: Public symbols exported by this module."""