"""Reset policies for the modular LNA environment.

This module defines reset behavior for simulator-backed LNA environments.
The reset helper supports explicit random reset and continuation from the
latest environment state. It can also optionally fall back to the most recent
valid simulator snapshot when repeated random-reset simulations fail.
"""

import time

from gym.utils import seeding


def reset_env(env, seed=None, options=None):
    """Reset an LNA environment instance.

    Parameters
    ----------
    env : LNAEnvBase
        Environment instance to reset. The environment is expected to provide
        initialization, state-update, fallback-restore, simulation-profile,
        and validity-flag attributes.
    seed : int or None, optional
        Random seed forwarded to Gym seeding utilities. If ``None``, a random
        seed is generated by Gym. The default is ``None``.
    options : dict[str, object] or None, optional
        Reset options. The dictionary must contain ``"reset_mode"``.
        Supported reset modes are ``"random"`` and ``"continue_last"``.

        ``"random"``
            Samples a new normalized design vector uniformly from the valid
            parameter range and evaluates it through the simulator.

        ``"continue_last"``
            Keeps the current environment state and resets only episode-local
            counters and flags while preserving objective values. If no
            current state exists, the function falls back to random reset.

    Returns
    -------
    init_state : numpy.ndarray
        Initial encoded state after reset.
    info : dict[str, object]
        Reset metadata containing reset mode, validity flags, and timing
        profile.

    Raises
    ------
    ValueError
        If ``reset_mode`` is missing from ``options`` or if an unsupported
        reset mode is requested.
    RuntimeError
        If random reset fails to obtain a valid initial simulation state and
        fallback restoration is unavailable or disabled.
    """

    reset_t0 = time.perf_counter_ns()
    options = options or {}

    if "reset_mode" not in options:
        raise ValueError(
            "reset_mode must be explicitly provided and must be either "
            "'random' or 'continue_last'."
        )

    requested_reset_mode = str(options["reset_mode"])

    if requested_reset_mode not in {"random", "continue_last"}:
        raise ValueError(f"Unknown reset_mode: {requested_reset_mode}")

    attempts = 0
    fallback_enabled = False

    if requested_reset_mode == "continue_last":
        if getattr(env, "state", None) is not None:
            env._initialization(preserve_objectives=True)
            reset_mode = "continue_last"
            init_state = env.state
        else:
            requested_reset_mode = "random"

    if requested_reset_mode == "random":
        if seed is not None:
            env.np_random, seed = seeding.np_random(seed)
        else:
            env.np_random, seed = seeding.np_random()

        env._initialization(preserve_objectives=False)

        max_reset_attempts = 10

        for _ in range(max_reset_attempts):
            attempts += 1
            x0 = env.np_random.uniform(0.0, env.max_param, env.action_dim)
            o, init_state = env._update_state(x0)

            if not env.is_non_convergent:
                reset_mode = "random"
                break
        else:
            fallback_after = max(
                1,
                int(getattr(env, "reset_fallback_after", max_reset_attempts)),
            )
            can_fallback = (
                bool(getattr(env, "allow_reset_fallback", False))
                and attempts >= fallback_after
                and getattr(env, "_last_valid_snapshot", None) is not None
            )

            if can_fallback:
                _, init_state = env._restore_last_valid_snapshot()
                reset_mode = "fallback_last_valid"
                fallback_enabled = True
            else:
                raise RuntimeError(
                    "RESET FAILED: unable to obtain a valid initial simulation "
                    "state. "
                    f"attempts={attempts}, "
                    f"last_simulation_error={env.last_simulation_error}"
                )

    env.state = init_state
    env.last_reset_profile = {
        "reset_mode": reset_mode,
        "attempts": attempts,
        "fallback_enabled": fallback_enabled,
        "total_ms": (time.perf_counter_ns() - reset_t0) / 1e6,
        "simulation_ms": env.last_simulation_profile.get("total_ms", 0.0),
        "requested_reset_mode": str(options["reset_mode"]),
    }

    info = {
        "reset_mode": reset_mode,
        "is_feasible": env.is_feasible,
        "is_non_convergent": env.is_non_convergent,
        "is_non_stable": env.is_non_stable,
        "is_invalid": env.is_invalid,
        "reset_profile": env.last_reset_profile,
    }

    return init_state, info