"""Thin bridge helpers between environments and the ngspice service layer.

This module provides small wrapper functions that connect LNA environment
objects to the ngspice simulation service. The helpers keep environment-side
attributes synchronized with simulator-side state while exposing a simple
function-level interface for simulation, workspace configuration, and cache
management.
"""

from pathlib import Path
from typing import Union

import numpy as np


def simulate(env, design_variables_config):
    """Evaluate one decoded design through the simulator service.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.
    design_variables_config : dict[str, float]
        Decoded simulator parameter mapping for the candidate circuit design.

    Returns
    -------
    performances : numpy.ndarray
        Simulated performance vector copied from the simulator result.
    stability_factor : float
        Stability factor returned by the simulator service.

    Raises
    ------
    RuntimeError
        If the simulator service reports an unsuccessful evaluation.
    """

    result = env.simulator.evaluate(design_variables_config)
    sync_simulator_state(env)

    if not result.ok:
        raise RuntimeError(result.error_message or "Simulation failed.")

    return np.array(result.performances, copy=True), float(result.stability_factor)


def reset_simulation_cache(env):
    """Clear the simulator-side memoized evaluation cache.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.

    Returns
    -------
    None
        The simulator cache is cleared and simulator-side state is mirrored
        back onto the environment.
    """

    env.simulator.reset_simulation_cache()
    sync_simulator_state(env)


def configure_workspace(
    env,
    *,
    project_name: str,
    run_id: str,
    run_root: Union[str, Path],
    worker_name: Union[str, int],
    scope: str = "train",
    clean: bool = False,
) -> None:
    """Bind the simulator service to a named workspace and synchronize state.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.
    project_name : str
        Project or experiment namespace used when constructing the workspace.
    run_id : str
        Unique run identifier.
    run_root : str or pathlib.Path
        Root directory under which simulator workspaces are created.
    worker_name : str or int
        Worker identifier used to isolate simulator files.
    scope : str, optional
        Workspace scope, such as ``"train"`` or ``"eval"``. The default is
        ``"train"``.
    clean : bool, optional
        Whether to clean the workspace before use. The default is ``False``.

    Returns
    -------
    None
        Workspace configuration is applied to the simulator service and the
        resulting simulator state is mirrored onto the environment.
    """

    env.simulator.configure_workspace(
        project_name=project_name,
        run_id=run_id,
        run_root=Path(run_root),
        worker_name=worker_name,
        scope=scope,
        clean=clean,
    )
    sync_simulator_state(env)


def make_simulation_cache_key(env, design_variables_config) -> tuple:
    """Build a simulator cache key for a decoded design.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.
    design_variables_config : dict[str, float]
        Decoded simulator parameter mapping for the candidate design.

    Returns
    -------
    tuple
        Hashable cache key generated by the simulator service.
    """

    return env.simulator.make_simulation_cache_key(design_variables_config)


def get_cached_simulation(env, cache_key):
    """Return a cached simulator result if one exists.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.
    cache_key : tuple
        Cache key produced by :func:`make_simulation_cache_key`.

    Returns
    -------
    object
        Cached simulator result if available, otherwise the simulator
        service's cache-miss value.
    """

    return env.simulator.get_cached_simulation(cache_key)


def store_cached_simulation(env, cache_key, performances, stability_factor) -> None:
    """Persist a simulator result in the service-side cache.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.
    cache_key : tuple
        Cache key associated with the evaluated design.
    performances : array-like or numpy.ndarray
        Simulated performance vector to cache.
    stability_factor : float
        Stability factor associated with the cached simulation result.

    Returns
    -------
    None
        The simulation result is stored in the simulator cache.
    """

    env.simulator.store_cached_simulation(
        cache_key,
        performances,
        stability_factor,
    )


def sync_simulator_state(env):
    """Mirror simulator-side state onto environment attributes.

    This function copies workspace handles, circuit handles, result paths,
    cache references, and profiling metadata from ``env.simulator`` to the
    environment object. It is used after simulator operations so that legacy
    environment code can continue to access simulator-related attributes
    directly from ``env``.

    Parameters
    ----------
    env : LNA_Environment_Base
        Environment instance containing a configured ``simulator`` service.

    Returns
    -------
    None
        Environment attributes are updated in place.
    """

    env.workspace = getattr(env.simulator, "workspace", None)
    env.spice_kernel = getattr(env.simulator, "spice_kernel", None)

    env.s_param_circuit = getattr(env.simulator, "s_param_circuit", None)
    env.nf_circuit = getattr(env.simulator, "nf_circuit", None)
    env.iip3_circuit = getattr(env.simulator, "iip3_circuit", None)

    env.dc_op_result_path = getattr(env.simulator, "dc_op_result_path", None)
    env.s_param_bandwidth_result_path = getattr(
        env.simulator,
        "s_param_bandwidth_result_path",
        None,
    )
    env.nf_result_path = getattr(env.simulator, "nf_result_path", None)
    env.iip3_result_path = getattr(env.simulator, "iip3_result_path", None)

    env.run_root = getattr(env.simulator, "run_root", None)

    env.last_simulation_error = getattr(
        env.simulator,
        "last_simulation_error",
        None,
    )
    env.last_simulation_profile = getattr(
        env.simulator,
        "last_simulation_profile",
        {},
    )
    env.simulation_profiles = getattr(env.simulator, "simulation_profiles", [])

    env.simulation_cache = getattr(env.simulator, "simulation_cache", {})
    env.simulation_cache_stats = getattr(
        env.simulator,
        "simulation_cache_stats",
        {},
    )